framework:
    directory:
        report: '/Reports/'
        script: '/subscripts/'
        test: '/Tests/'
        working: '/working/'
region:
    region1:
        name: dsclab
        ipaddress: IPADDRESS
        cliusername: CLIUSER
        clirootpassword: CLIPASSWORD
        sympaccount: SYMPHONYCLOUDACCOUNT
        sympusername: SYMPHONYUSERNAME
        symppassword: SYMPHONYPASSWORD
errortypes:
    0: SUCCESS
    1: WARN
    2: ERROR
    3: CRITICAL
    4: UNDEFINED
formatting:
    linebreak: '-------------------------------------------------------------------------------------------------------'