region:
    region1:
        name: dsclab
        ipaddress: IPADDRESS
        cliusername: CLIUSER
        clirootpassword: CLIPASSWORD
        sympaccount: SYMPHONYCLOUDACCOUNT
        sympusername: SYMPHONYUSERNAME
        symppassword: SYMPHONYPASSWORD
    email:
        server: smtp.mweb.co.za
        port: 587
        user: username
        password: mypassword
framework:
    directory:
        report: 'reports'
        script: 'scripts'
        test: 'tests'
        working: 'working'
    errortypes:
        0: SUCCESS
        1: WARN
        2: ERROR
        3: CRITICAL
        4: UNDEFINED
    formatting:
        linebreak: '---------------------------------------------------------------------------------------------------'