region:
    region1:
        name: 'REGION-NAME'
        ipaddress: 'REGION-IP-ADDRESS'
        cliusername: CLIUSER
        clirootpassword: CLIPASSWORD
        sympaccount: 'SYMPHONY-ADMIN-ACCOUNT'
        sympusername: 'SYMPHONY-USER-NAME'
        symppassword: 'SYMPHONY-USER-PASSWORD'
    email:
        server: 'E-MAIL-SERVER'
        recipients: ['recipient01@domain.com','recipient02@domain.com','recipient03@domain.com']
        port: '25'
        fromaddress: 'senderaddress@domain.com'
        user: "username"
        password: "password"
framework:
    directory:
        report: 'reports'
        reportcount: '500'
        script: 'tests/scripts'
        test: 'tests'
        working: 'tests/working'
    errortypes:
        0: HEALTHY
        1: WARNING
        2: ERROR
        3: CRITICAL
        4: UNDEFINED
        5: INFORMATION
    formatting:
        linebreak: '---------------------------------------------------------------------------------------------------'
