region:
    region1:
        name: absaprd01
        ipaddress: 22.240.212.1
        clirootpassword: rackattack
        sympaccount: cloud_admin
        sympusername: admin
        symppassword: Str@t0sc@l3.absa!
    email:
        server: 'gexc.absa.co.za'
        port: '25'
        user: ""
        password: ""
framework:
    directory:
        report: 'reports'
        script: 'scripts'
        test: 'tests'
        working: 'working'
    errortypes:
        0: SUCCESS
        1: WARN
        2: ERROR
        3: CRITICAL
        4: UNDEFINED
    formatting:
        linebreak: '---------------------------------------------------------------------------------------------------'
