region:
    region1:
        ipaddress: *********
        cliusername: *********
        clirootpassword: *********
        sympaccount: **********
        sympusername: **********
        symppassword: **********
errortypes:
    0: SUCCESS
    1: WARN
    2: ERROR
    3: CRITICAL