region:
    region1:
        name: REGIONNAME
        ipaddress: IPADDRESS
        cliusername: CLI-USER
        clirootpassword: CLI-PASSWORD
        sympaccount: SYMPHONY-CLOUD-ACCOUNT
        sympusername: SYMPHONY-USERNAME
        symppassword: SYMPHONY-PASSWORD
    email:
        server: 'SERVER-FQDN'
        recipients: ['PERSON01@DOMAIN.COM','PERSON02@DOMAIN.COM','PERSON03@DOMAIN.COM']
        port: 'MAIL-SERVER-PORT'
        user: "username"
        password: "password"
framework:
    directory:
        report: 'reports'
        reportcount: '500'
        script: 'scripts'
        test: 'tests'
        working: 'working'
    errortypes:
        0: HEALTHY
        1: WARNING
        2: ERROR
        3: CRITICAL
        4: UNDEFINED
    formatting:
        linebreak: '---------------------------------------------------------------------------------------------------'