region_access:
  ipaddress: 'IPADDR'
  cloud_domain: 'DOMAIN'
  cloud_user: 'USERNAME'
  cloud_password: 'PASSWORD'
  project: 'PROJECTNAME'
purestoragearray:
  ipaddress: 'IPADDR'
  apitoken: 'APITOKEN'